version: "3.7"
services:
 # Banco de dados usado pela aplicacao
 mysql:
  container_name: mysql
  image: mysql:latest 
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: "webflux"
  ports:
   - 3306:3306

 grafana:
  image: grafana/grafana:latest
  container_name: grafana
  restart: always
  ports:
   - 3000:3000
  networks:
   - grafana_network
  environment:
   - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
   - GF_AUTH_ANONYMOUS_ENABLED=true
   - GF_AUTH_BASIC_ENABLED=false
  volumes:
   - grafana_data:/var/lib/grafana
  depends_on:
   - influxdb

 influxdb:
  image: influxdb:1.8
  container_name: influxdb
  restart: always
  ports:
   - 8086:8086
   - 8082:8082
  networks:
   - grafana_network
  volumes:
   - influxdb_data:/var/lib/influxdb
  environment:
   - INFLUXDB_DB=grafana
   - INFLUXDB_USER=grafana
   - INFLUXDB_USER_PASSWORD=password
   - INFLUXDB_ADMIN_ENABLED=true
   - INFLUXDB_ADMIN_USER=admin 
   - INFLUXDB_ADMIN_PASSWORD=password 

 k6:
  container_name: k6
  image: loadimpact/k6:latest
  networks:
   - grafana_network
  ports:
   - "6565:6565"
  environment:
   - K6_OUT=influxdb=http://influxdb:8086/grafana
  volumes:
   - ./scripts:/scripts

networks:
  grafana_network:
volumes:
  grafana_data:
  influxdb_data: